
org.gradle.jvmargs=-Xmx12G



# org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
org.gradle.java.home=C:\\Program Files\\Amazon Corretto\\jdk1.8.0_472\\website_link=https://modrinth.com/mod/slice
issues_link=https://github.com/ansi-sudo/Slice/issues
source_link=https://github.com/ansi-sudo/Slice
kofi_link=https://ko-fi.com/ansi
