name: Bug report
description: Report a bug you found
title: '[Bug] '
labels: ''
assignees: ''
body:
  - type: dropdown
    id: loader
    attributes:
      label: Loader
      description: Which loader are you using?
      options:
        - Loader A
        - Loader B
        - Loader C
    validations:
      required: true