name: Bug report yml
description: Report a bug you found
title: '[Bug] '
labels: []
assignees: []
body:
  - type: dropdown
    id: loader
    attributes:
      label: Loader
      options:
        - Option 1
        - Option 2
        - Option 3
        - Option 4
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the bug...
    validations:
      required: true

  - type: input
    id: field1
    attributes:
      label: Field 1
      placeholder: Enter text...
    validations:
      required: true

  - type: input
    id: field2
    attributes:
      label: Field 2
      placeholder: Enter text...
    validations:
      required: true